### ISSUE TITLE
Set up Issue Templates for Project Goose

### ISSUE THREAD

**Issue by jhacksman** [jhacksman/project-goose#2]
# Issue 2: Set up Issue Templates  

## Description
Set up issue templates for bug reports and feature requests in the Project Goose repository.

### Tasks
- [ ] Create `bug_report.md` file in root
- [ ] Create `feature_request.md` file in root
- [ ] Move these files to `.github/ISSUE_TEMPLATE/` folder
